version: 2
jobs:
  build:
    docker:
#      - image: circleci/node:12.22.5
      - image: circleci/node:12.2.0
#      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/projects
#    environment:
#        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    steps:
      - checkout
      - run: java --version
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run WebdirverIO tests
          command: |
            npm test ./tests/e2e/config/wdio.chrome.conf.js
          no_output_timeout: 30m
      - run:
          name: Run WebdirverIO tests
          command: |
            npm test ./tests/e2e/config/wdio.firefox.conf.js
          no_output_timeout: 30m
      - store_test_results:
          path: ./wdio-logs

      - store_artifacts:
          path: ./screenShots/

      - store_artifacts:
          path: ./errorShots/
